// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq3k5dqMC6HKxS0H9_ynAx6Ohb6Qz8tmI',
    appId: '1:169654985938:web:b43708ffbf769ee7b4b90b',
    messagingSenderId: '169654985938',
    projectId: 'tugas-8-cf2c2',
    authDomain: 'tugas-8-cf2c2.firebaseapp.com',
    storageBucket: 'tugas-8-cf2c2.firebasestorage.app',
    measurementId: 'G-FK6N1HZZT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuis5R3cBTO4e8P6u-kwxyXxu9mf4YUOw',
    appId: '1:169654985938:android:971e53c801780d34b4b90b',
    messagingSenderId: '169654985938',
    projectId: 'tugas-8-cf2c2',
    storageBucket: 'tugas-8-cf2c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHT7j2WfXbaDBcsmrnW0gb9H4WLuWohYs',
    appId: '1:169654985938:ios:12dba09dcf1d61cab4b90b',
    messagingSenderId: '169654985938',
    projectId: 'tugas-8-cf2c2',
    storageBucket: 'tugas-8-cf2c2.firebasestorage.app',
    iosBundleId: 'com.example.panasss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHT7j2WfXbaDBcsmrnW0gb9H4WLuWohYs',
    appId: '1:169654985938:ios:12dba09dcf1d61cab4b90b',
    messagingSenderId: '169654985938',
    projectId: 'tugas-8-cf2c2',
    storageBucket: 'tugas-8-cf2c2.firebasestorage.app',
    iosBundleId: 'com.example.panasss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq3k5dqMC6HKxS0H9_ynAx6Ohb6Qz8tmI',
    appId: '1:169654985938:web:1d44fb0546ddc87cb4b90b',
    messagingSenderId: '169654985938',
    projectId: 'tugas-8-cf2c2',
    authDomain: 'tugas-8-cf2c2.firebaseapp.com',
    storageBucket: 'tugas-8-cf2c2.firebasestorage.app',
    measurementId: 'G-5N24W56LDK',
  );
}
